apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace-config.yaml
  - 02-istio-service-mesh.yaml
  - backend-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: landing-zone-portal
  managed-by: kustomize
